name: Analyze Code Quality
description: Perform static analysis with Psalm
runs:
  using: composite
  steps:
    - name: Cache Dependencies
      id: cache
      uses: stafftastic/laravel-actions/cache@v1.0.0
      with:
        require-hit: true
    - name: Run Static Analysis
      shell: bash
      run: |
        ./vendor/bin/psalm --php-version=8.0
