name: Check for Copy-Pasted Code
description: Check for copy-pasted code with phpcpd
inputs:
  min-lines:
    description: The minimum lines to count as repeated code
    required: true
    default: 50
runs:
  using: composite
  steps:
    - name: Cache Dependencies
      id: cache
      uses: stafftastic/laravel-actions/cache@main
      with:
        require-hit: true
    - name: Run Copy-Paste Check
      shell: bash
      run: |
        test -f phpcpd.phar || curl -L https://phar.phpunit.de/phpcpd.phar -o phpcpd.phar
        php phpcpd.phar src --min-lines=${{inputs.min-lines}}
